### ISSUE TITLE
Drag / mobile support?

### ISSUE THREAD

**Issue by M1chaelTran** [Carr1005/react-carousel-slider#1]
Does this slider support for desktop drag or mobile?

**Comment by Carr1005** [comment]
@M1chaelTran sorry that the component is still not supporting 'drag' on desktop now but it does support 'swipe' events when mobile device viewport is detected, events would be registered automatically. 
Maybe you could have a try in  [Demo](http://carr1005.github.io/react-carousel-slider/index.html) by your mobile.

**Comment by Carr1005** [comment]
@M1chaelTran, now the slider support drag event on the mobile and desktop ! 
[Demo](http://carr1005.github.io/react-carousel-slider/index.html)
Thanks for your attention that actually pushes this feature come.
